---
title: "WMDuggan"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

# Core
library(tidyverse)
library(tidyquant)

# Interactive Visualization
library(plotly)

# Database
library(odbc)
library(RSQLite)
```

```{r}
con <- dbConnect(RSQLite::SQLite(), "../00_data/bikes_database.db")

# dbListTables(con) to connect and list tables in a database. When building Web Apps, speed is important. To improve use the database to manipulate data and perform in separate space like this within SQL.
bikes_tbl <- tbl(con, "bikes")
bikeshops_tbl <- tbl(con, "bikeshops")
orderlines_tbl <- tbl(con, "orderlines")
# Mutate used to add new columns to dataframe or modify existing columns
processed_data_tbl <- orderlines_tbl %>%
    left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id")) %>%
    left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
    mutate(extended_price = quantity * price) %>%
    collect()
# Takes processed tbl and performs date, +new cols operations
processed_data_tbl <- processed_data_tbl %>%
    mutate(order.date = ymd(order.date)) %>%
    separate(location, into = c("city", "state"), sep = ", ") %>%
    select(order.date, order.id, order.line, state, quantity, price, extended_price)
    
# processed_data_tbl

dbDisconnect(con)
```

Column {data-width=1000}
-------------------------------------------------------------------------------

### By State

```{r}
geo_plot_tbl <- processed_data_tbl %>%
    group_by(state) %>%
    summarise(total_revenue = sum(extended_price)) %>%
    ungroup() %>%
    mutate(label_text = str_glue("State: {state}
                                 Revenue: {scales::dollar(total_revenue)}"))
```

```{r}
geo_plot_tbl %>% # Need internet connection for this
    plot_geo(locationmode = "USA-states") %>%
    add_trace(z = ~total_revenue, 
              locations = ~state, 
              color = ~total_revenue, 
              text = ~label_text, 
              colors = "Blues") %>% 
    layout( 
        geo = list( 
            scope = "usa", 
            projection = list(type = "albers usa"),
            showlakes = TRUE, 
            lakecolor = toRGB("white")
            ) 
        )
```

